### ISSUE TITLE
schema_statements.rb:130 `new_column_from_field': wrong number of arguments (given 3, expected 2)

### ISSUE THREAD

**Issue by jbwl** [PNixx/clickhouse-activerecord#100]
**Rails:** 7.1.1
**Ruby:** 3.2.2
**Gem:** clickhouse-activerecord 0.15.5, branch: rails_7 (latest version)

**Model**:
```
class Product < ApplicationRecord
  self.is_view = false
  establish_connection :clickhouse_production
end
```

**What is expected to happen:**

A query on the Model should be executed.
Examples: 
`Product.count`
`Product.where(product_type: 'car').maximum(:price)`

**What actually happens:** 

Whenever I try use a query method on a model, the error occurs:
`/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/bundler/gems/clickhouse-activerecord-7e6206e6016b/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:130:in "new_column_from_field": wrong number of arguments (given 3, expected 2) (ArgumentError)`

**Comment by PNixx** [comment]
Fixed in `rails_7` branch
