### ISSUE TITLE
FINAL function for FROM operator raises error 

### ISSUE THREAD

**Issue by TemaMix** [PNixx/clickhouse-activerecord#102]
After the https://github.com/PNixx/clickhouse-activerecord/issues/81 changes I run into with issue related to Clickhouse version 22.9.1, 
In my case FINAL option works only for ReplacingMergeTree type of structure and raises error for MergeTree.

the error happens when I try to execute rake db:migrate command (rails 6.1.7.6, ruby 2.7.6)

the query that raises error:
SELECT ar_internal_metadata.* FROM ar_internal_metadata FINAL WHERE ar_internal_metadata.key = 'environment' LIMIT 1 FORMAT JSONCompact;

error message:
<Error> executeQuery: Code: 181. DB::Exception: Storage MergeTree doesn't support FINAL. (ILLEGAL_FINAL) (version 22.9.1.1525 (official build)) (from [::1]:55242) (in query: SELECT ar_internal_metadata.* FROM ar_internal_metadata FINAL WHERE ar_internal_metadata.key = 'environment' LIMIT 1 FORMAT JSONCompact), Stack trace (when copying this message, always include the lines below):

SELECT name, engine FROM system.tables;
─name──────────────────┬─engine─────────────┐
│ ar_internal_metadata                                          │ MergeTree

**Comment by PNixx** [comment]
You need drop table `ar_internal_metadata` after update gem.
