### ISSUE TITLE
Clickhouse ActiveRecord query working on Rails/ActiveRecord 7.1.0alpha but not on ActiveRecord 7.1.2

### ISSUE THREAD

**Issue by Anirudh2011** [PNixx/clickhouse-activerecord#106]
I'm trying to run a query 
`Model.where(id in [1])`
which is working when ActiveRecord version is `activerecord (= 7.1.0.alpha)`
but since I upgraded rails to 7.1.2 
the same query throws error. The issue seems to be in this function `new_column_from_field` of clickhouse-activerecord
<img width="1062" alt="Screenshot 2023-11-28 at 4 12 22 PM" src="https://github.com/PNixx/clickhouse-activerecord/assets/37499515/43608d6a-f896-4682-8cea-85b5c9e0d024">
<img width="944" alt="Screenshot 2023-11-28 at 4 13 44 PM" src="https://github.com/PNixx/clickhouse-activerecord/assets/37499515/0f9dd15b-dcb3-40ff-8b14-e8d0a2135bab">

Any help would be appreciated
Thanks

**Comment by DimitriosLisenko** [comment]
Also seeing this.

**Comment by PNixx** [comment]
fixed in `v1.0.0`
