### ISSUE TITLE
Issue related with config.use_transactional_fixtures = true

### ISSUE THREAD

**Issue by TemaMix** [PNixx/clickhouse-activerecord#107]
I use rails 7, clickhouse-activerecord and rspec.

To improve performance I use `config.use_transactional_fixtures = true` but the clickhouse-activerecord does not supproted and it follows to error:

/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:113:in `write_query?'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:360:in `mark_transaction_written_if_write'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:519:in `internal_execute'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/savepoints.rb:12:in `create_savepoint'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:337:in `materialize!'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:449:in `block in begin_transaction'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:416:in `begin_transaction'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:533:in `block in within_new_transaction'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `handle_interrupt'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:23:in `block in synchronize'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `handle_interrupt'
/activesupport-7.1.2/lib/active_support/concurrency/load_interlock_aware_monitor.rb:19:in `synchronize'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/activerecord-7.1.2/lib/active_record/transactions.rb:361:in `with_transaction_returning_status'
/activerecord-7.1.2/lib/active_record/transactions.rb:309:in `save'
/activerecord-7.1.2/lib/active_record/suppressor.rb:52:in `save'
/activerecord-7.1.2/lib/active_record/persistence.rb:38:in `create'

Do you have any ideas how to fix it and use config.use_transactional_fixtures = true ?

**Comment by PNixx** [comment]
ClickHouse does not support transactions.
