### ISSUE TITLE
How to config multiple nodes? 

### ISSUE THREAD

**Issue by PoroshkinaVV** [PNixx/clickhouse-activerecord#124]
I have some settings in my database.yml
```
  default: &default
  adapter: clickhouse
  database: <%= ENV.fetch('CLICKHOUSE_DATABASE', '') %>
  host: <%= URI.parse(ENV["CLICKHOUSE_SERVERS"].split(',').first).host %>
  port: <%= URI.parse(ENV["CLICKHOUSE_SERVERS"].split(',').first).port %>
  username: <%= ENV["CLICKHOUSE_USERNAME"] %>
  password: <%= ENV["CLICKHOUSE_PASSWORD"] %>
  ssl: false # optional for using ssl connection
  debug: true # use for showing in to log technical information
  migrations_paths: db/migrate_clickhouse # optional, default: db/migrate_clickhouse
```

My variable ENV["CLICKHOUSE_SERVERS"] contains multiple urls. How can I set clickhouse to use them all?

**Comment by PoroshkinaVV** [comment]
@astudnev's PR #22 has cluster configuration, that could be helpful to my purpose. 
@PNixx, what do you think about configuring multiple urls?

**Comment by PNixx** [comment]
@PoroshkinaVV you can use haproxy. This is the best solution.

**Comment by PoroshkinaVV** [comment]
Thanks for your advice.
But why don't you want to add such feature to your gem? 
Even old, non-supported now https://github.com/archan937/clickhouse has it.

I really want to use clickhouse-activerecord as far as I can. What if I try to make a PR for multiple urls in cluster?

**Comment by PNixx** [comment]
```ruby
class ActionView < ActiveRecord::Base
  establish_connection(
    adapter: 'clickhouse',
    database: 'database',
    connection: Net::HTTP.start('http://example.org', 8123)
  )
end
```

You can use custom connection class

**Comment by PoroshkinaVV** [comment]
That's not my case. I have multiple servers in cluster, data is replicated. 
I need opportunity to use each of them at the same time

**Comment by PNixx** [comment]
I understand. My company also has ClickHouse servers in a cluster, haproxy helps us a lot. Ruby should not be involved in balancing traffic, there are other, more suitable tools for this.

**Comment by PNixx** [comment]
Or, you can see github workflow https://github.com/PNixx/clickhouse-activerecord/blob/master/.docker/docker-compose.cluster.yml balancing with nginx.

**Comment by PoroshkinaVV** [comment]
@PNixx thanks for adding examples! Updating... Will try to config nginx.
