### ISSUE TITLE
t.column Should Default to Null: false

### ISSUE THREAD

**Issue by ericbeland** [PNixx/clickhouse-activerecord#135]
In a migration using the .column method, with a CODEC, if you don't set null: false, it will wrap nullable around the definition string for the column and produce invalid SQL.

```
# doesn't work:
   t.column :request_body_size, "Nullable(UInt64) CODEC(T64, LZ4)"
   
# works fine   
   t.column :request_body_size, "Nullable(UInt64) CODEC(T64, LZ4)", null: false
```

It might make sense to make the default `null: false` for .column so it doesn't attempt to wrap nullable around the string with the codec in it.

**Comment by PNixx** [comment]
Fixed in v1.2.0
