### ISSUE TITLE
Update record field

### ISSUE THREAD

**Issue by xao0isb** [PNixx/clickhouse-activerecord#155]
Is there any way to update record field? If I use `update` or change the value of a record and then run `save` the value in database remains the same.

**Comment by PNixx** [comment]
Already support in latest versions https://github.com/PNixx/clickhouse-activerecord/blob/master/spec/single/model_spec.rb#L72-L86

**Comment by xao0isb** [comment]
I'm using latest version

```ruby
record = Model.create(value: "abc")
pp record.value # "abc"

record.update!(value: "123")
pp record.value # "123"

pp Model.last.value # "abc" and not "123"
```

**Comment by xao0isb** [comment]
@PNixx reopen issue, please

**Comment by PNixx** [comment]
Need more details: ClickHouse version, table structure and engine.

**Comment by xao0isb** [comment]
- ClickHouse version: 24.7.2.13
- clickhouse-activerecord gem version: 1.0.13
- Table:
```ruby
create_table :users, id: false, options: "MergeTree PRIMARY KEY (uuid)" do |t|
  t.column :uuid, "UUID", null: false
  t.string :name, null: false

  t.timestamps
end
```

Am I doing something wrong with table creation? I don't get deep into clickhouse yet and now just want to test it out.

**Comment by PNixx** [comment]
I ran the test and it completed successfully with a one second pause. You need to wait some time before receiving data from the database. Updating and deleting in Clickhouse should only be used in extreme cases https://clickhouse.com/docs/en/guides/developer/mutations
<img width="448" alt="image" src="https://github.com/user-attachments/assets/e9d3da2a-ab37-4b82-8890-f60f072f59c0">
