### ISSUE TITLE
Support for rails 7.2

### ISSUE THREAD

**Issue by jenskdsgn** [PNixx/clickhouse-activerecord#156]
We were trying to update rails from 7.1.3.4 to 7.2. 

Booting the app shows the following error message:

```
gems/3.3.0/gems/activerecord-7.2.0/lib/active_record/connection_adapters.rb:85:in `resolve':
Database configuration specifies nonexistent 'Clickhouse' adapter.
Available adapters are: mysql2, postgresql, sqlite3, trilogy.
Ensure that the adapter is spelled correctly in config/database.yml and that you've
added the necessary adapter gem to your Gemfile and that it is at its latest version.
If it is up to date, the adapter may need to be modified. (ActiveRecord::AdapterNotFound)
```

After some digging through the rails diff, I came across a bunch of changes in AR and how they load custom adapters.
They decided on a new interface:

https://github.com/rails/rails/commit/009c7e74117690f0dbe200188a929b345c9306c1

[This change](https://github.com/rails/rails/commit/fd24e5bfc9540fc00764a59ddf39a993bbd63ba2) also has high potential to screw up the internals of this adapter.

Let me know if you consider any help from our side to fix this. Since this might be a bigger task, is there any initial feeling you are having with this in terms of timeline?

Thanks.

**Comment by PNixx** [comment]
Released [v1.1.0](https://github.com/PNixx/clickhouse-activerecord/releases/tag/v1.1.0)
