### ISSUE TITLE
Do we have any method what will return "Final" result from ClickHouse ?

### ISSUE THREAD

**Issue by Kondzolko** [PNixx/clickhouse-activerecord#24]
Hello everyone, today I stuck with one interesting problem, after I deleted a record, to see current version of my db I need run command "FINAL", I research your gem and didn't get any method how I can add this "FINAL" method to my query.

Can you tell me please if you have this functionality?

This is an example of what I mean.
https://ruhighload.com/%D0%A3%D0%B4%D0%B0%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5+%D0%B8+%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5+%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85+%D0%B2+clickhouse

Best regards,
Andrew

**Comment by PNixx** [comment]
You can use in from request, for example:
```
Action.from('actions FINAL').count
```

**Comment by Kondzolko** [comment]
Thank you.
