### ISSUE TITLE
#typo at Instead of StandartError, there should be StandardError

### ISSUE THREAD

**Issue by AntonKolmakov** [PNixx/clickhouse-activerecord#29]
https://github.com/PNixx/clickhouse-activerecord/blob/05d717b769ced10f42c99b6b16051b570417dd90/lib/active_record/connection_adapters/clickhouse/schema_statements.rb#L20

**Comment by StoneGod** [comment]
this is can be close

https://github.com/PNixx/clickhouse-activerecord/pull/30

**Comment by tuwilof** [comment]
@PNixx hello! Could you release a new version with this fix? 🚀
