### ISSUE TITLE
Ruby 3.0.0 compatibility issue

### ISSUE THREAD

**Issue by annalisa2014** [PNixx/clickhouse-activerecord#38]
Hello,
I'm receiving errors while performing every migrations with Ruby 3.0.0. I tried with both Clickhouse as unique db and with Clickhouse as secondary db (so changing `database.yml` accordingly). In both cases I receive following stack trace:

```
bundle exec rake db:migrate --trace
** Invoke db:migrate (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:migrate
rake aborted!
ArgumentError: wrong number of arguments (given 3, expected 2)
..versions/3.0.0/lib/ruby/gems/3.0.0/gems/clickhouse-activerecord-0.4.8/lib/active_record/connection_adapters/clickhouse/schema_definitions.rb:10:in `initialize'
```

This error is thrown with all migrations of different kind. I even tried with migrations from yours examples and they failed too.
Regressing to ruby 2.7.2 solves the problem and all works perfectly. Thanks in advance and hoping for future releases :)

**Comment by bdevel** [comment]
I poked at this for a while but had different issues all together. I couldn't the the test to run without significant issue on any version of Ruby - though they did seem to give different errors. It doesn't appear to be a compatibility issue with Ruby versions for parameter expansion, ex, `t.string :version, **version_options` as I tested that in IRB with a few different versions of Ruby.
