### ISSUE TITLE
Array types support

### ISSUE THREAD

**Issue by MauricioMoraes** [PNixx/clickhouse-activerecord#41]
As I've seen [here](https://github.com/PNixx/clickhouse-activerecord/blob/42f6077dd97b5805ce53cd2f52cfccd52e9a9f6c/lib/active_record/connection_adapters/clickhouse_adapter.rb), the adapter still doesn't suport Array types. Is it correct? 

### Background - My 'array of uints' field being recognized as integers
I created an array of uints field:

```sql
    CREATE TABLE my_table
      (
          (...)
          `my_field` Array(Nullable(UInt32)),
          (...)
      )
      ENGINE=MergeTree() 
```

And set the values via sql. 

But when I tried to recover the value of the field using active record, it interpreted the field as integer:

```ruby
MyModel.my_field # => *** NoMethodError Exception: undefined method 'to_i' for [123, 999]:Array
```

If I reload the console and try to fetch the object, I get: 

```ruby
MyModel.last # => (Object doesn't support #inspect)
```
Obs: This is a more serious problem, because it prevents me of creating a custom getter method.

Has anyone tried creating array fields on Clickhouse with this gem yet? 

Is there any alternative for this use case so far? Json fields or other substitute data type? 

### Possible workaround - Custom getter method
If the object load didn't fail, I could write the getter method myself. 
How can I bypass that object load error so I can write my getter method:

```ruby
class MyModel < ...
   def my_method
     # custom getter
   end
...
end
```

Thanks a lot!

**Comment by PNixx** [comment]
Support added to 0.5.1 version (https://github.com/PNixx/clickhouse-activerecord/commit/9aad51f4840b249ddfa9f9c316d3d35df7d66465)
