### ISSUE TITLE
Supporting multiple upstream servers?

### ISSUE THREAD

**Issue by mzealey** [PNixx/clickhouse-activerecord#42]
I wonder if it would be possible to add support to allow us to specify an array of servers to which the code could connect to? The use-case is that we might have a few identical clickhouse servers and we want to try any of them, but if one fails we would like it to retry on another. Looking through the code I guess the way to do this would be to modify https://github.com/PNixx/clickhouse-activerecord/blob/master/lib/active_record/connection_adapters/clickhouse_adapter.rb#L328 to create a new object (rather than `Net::HTTP`) which encapsulates the logic so that when `.post()` function is called it will try one server at random, if that fails (for connect reasons) it will try another etc up to a couple of retries? Is there a way to either implement this directly in the package, or provide a way for us to easily pass in our own alternative connection handling class which does this multi server retry logic?

**Comment by PNixx** [comment]
I use haproxy for these purposes.

**Comment by mzealey** [comment]
But then haproxy (or chproxy or whatever) becomes the point of failure. How about putting a patch in like https://github.com/mzealey/clickhouse-activerecord/commit/9e3273c44e2b19bf29cab3de44fa548db2ba673e which would allow someone to specify their own connection object and we can then easily create our own one with the same interface that handles the retries?

**Comment by PNixx** [comment]
You can install haproxy locally on every server that connects to the clickhouse. It has been working for us for many years and has never had any problems.

**Comment by mzealey** [comment]
Is there any reason you would not be able to merge these internal extensions to the driver so that we can pass a connection in directly though? It may also help with other situations where the Net::HTTP object wants more customization than is allowed at present (eg around ssl flags, timeouts etc).
