### ISSUE TITLE
Codec support in migrations?

### ISSUE THREAD

**Issue by jlholm** [PNixx/clickhouse-activerecord#55]
Hey @PNixx, thanks for your work on this gem!

As the title mentions, I'm wondering if Codecs are supported in migrations. Here's an example of a Clickhouse table creation that uses a Codec for compression on the `timestamp` column.

```sql
CREATE TABLE IF NOT EXISTS metrics (
  name String,
  timestamp DateTime('UTC') CODEC(DoubleDelta, LZ4),
  value Int64,
  organization_id UInt32
) ENGINE = MergeTree()
  PARTITION BY toYYYYMMDD(timestamp)
  ORDER BY (name, organization_id, timestamp)
  PRIMARY KEY (name, organization_id, timestamp)
  SETTINGS index_granularity=8192;
```

Is it possible to apply this Codec using your Clickhouse `create_table` DSL?

**Comment by PNixx** [comment]
No, but you can use raw column data:
```
t.column : timestamp, 'DateTime('UTC') CODEC(DoubleDelta, LZ4)'
```
