### ISSUE TITLE
EOFError error

### ISSUE THREAD

**Issue by SerjSivkov** [PNixx/clickhouse-activerecord#58]
When AR requests through this gem, an error falls on the sample
`EOFError: end of file reached: SELECT resource_records.external_id FROM resource_records WHERE resource_records.resource_type = 'resource_5000' AND resource_records.external_id IN ('1579', '1565')`

Is it possible to re-send the request when this error occurs?

**Comment by PNixx** [comment]
The ClickHouse server terminated the connection unexpectedly. You must handle such exceptions yourself and re-request if necessary.
https://clickhouse.com/docs/en/introduction/performance/
