### ISSUE TITLE
"Clickhouse delete is not supported" why is that?

### ISSUE THREAD

**Issue by 1c7** [PNixx/clickhouse-activerecord#74]
Hi, I am getting this message

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/1804755/183113866-6a96347d-54c9-48fc-9a90-a23870861ca8.png">

I am not sure this is a feature or bug.
I should be allow to run `destory_all`

**Comment by 1c7** [comment]
```
TRUNCATE TABLE [table_name]
```

this sql works for me

**Comment by PNixx** [comment]
Clickhouse does not support deleting data from a table. The truncate command is used to clear the entire table.
