### ISSUE TITLE
ch can now delete - Model.delete_all leads to error: delete is not supported

### ISSUE THREAD

**Issue by schorsch** [PNixx/clickhouse-activerecord#79]
See the [clickhouse docs for delete](https://clickhouse.com/docs/en/sql-reference/statements/delete)

I'll see if i can fix that in my fork.

**Comment by PNixx** [comment]
This is experimental function

**Comment by schorsch** [comment]
uups, yes just stumbled into this error msg:

` Lightweight delete mutate is experimental. Set `allow_experimental_lightweight_delete` setting to enable it`

Still diving into the details of CH, wonder how to get rid of the data without creating a new table.

**Comment by PNixx** [comment]
You can use https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/collapsingmergetree/ or https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree

**Comment by schorsch** [comment]
Thanks for the hint, i'll dive into it!

**Comment by brookemckim** [comment]
@PNixx this is no longer experimental as of 23.3.

**Comment by PNixx** [comment]
Thanks, I'll check it

**Comment by PNixx** [comment]
Released in v1.0.1
