### ISSUE TITLE
Array(DateTime) columns loading as null

### ISSUE THREAD

**Issue by ottony** [PNixx/clickhouse-activerecord#83]
When there's an array column with _DateTime_ (e.g. `Array(DateTime)`), it's loaded as `nil` even if not null.

**Example:**
```SQL
-- `array_column` Array(DateTime)

INSERT INTO sample_table (id, array_column) VALUES (1, '[''2022-12-06 15:22:49'',''2022-12-06 15:22:49'']')
```

```ruby
> SampleTable.find(1).as_json
 => {"array_column" => nil, "id" => 1}
```

Removing the [OID::Array :datetime](https://github.com/PNixx/clickhouse-activerecord/blob/master/lib/active_record/connection_adapters/clickhouse/oid/array.rb#L13-L16) subtype or changing to any other like _:string_, _:integer_ or _:DateTime_, seems to load the value as a string.

```ruby
class Array < Type::Value # :nodoc:
  def initialize(sql_type)
    @subtype = case sql_type
      when /U?Int\d+/
        :integer
      when /DateTime/
        :integer
      when /Date/
        :date
      else
        :string
      end
  end
  
  ...
end
```

**After:**

```ruby
> SampleTable.find(1).as_json
 => {"array_column" => ["2022-12-06 15:22:49", "2022-12-06 15:22:49"], "id" => 1}
 
> SampleTable.find(1).array_column.map(&:class)
 => [String, String]
```

Version:
- rails 6.1.7
- clickhouse-activerecord 0.5.11
- ClickHouse 22.8.6.71

**Comment by PNixx** [comment]
Please write your version of ClickHouse and Rails
