### ISSUE TITLE
Support for the Map data type

### ISSUE THREAD

**Issue by brookemckim** [PNixx/clickhouse-activerecord#85]
I am using the Map data type and currently it comes through as an escaped Ruby hash. Just calling `eval` on it converts it to a Hash, but I'd like to add official support. Let me know if there is any guidance on where to begin with this. 

This is what the ruby class looks like unserialized:
```
 metadata: "{\"Version\"=>\"v2\", \"Type\"=>\"Data\"}",
```

**Comment by PNixx** [comment]
Please provide a link to the official documentation. I don't understand what type it is.

**Comment by brookemckim** [comment]
https://clickhouse.com/docs/en/sql-reference/data-types/map
