### ISSUE TITLE
Integer wrongly typecasted to strings in certain situations

### ISSUE THREAD

**Issue by jbwl** [PNixx/clickhouse-activerecord#92]
Gem version: 0.5.15 / branch: rails_7
Rails version: 7.0.8 (also tested on 6.x)

Expected result: This adapter should not cast int values to strings when a sum() with no column alias or an arbitrary alias is being used, like the MySQL adapter can.
Actual result: This adapter fails to typecast correctly when either no, or an arbitrary alias is applied to a summed int column.

This works correctly:
```
=> MyModel.select("productid,sum(units) as units").group('productid').where(productid: 'abc')

#<MyModel:0x0000ffff8f682448> {
         "productid" => "abc",
         "units" => 999
    }
```

This does not (no alias name on sum column) leads to int value being cast to string:
```
=> MyModel.select("productid,sum(units)").group('productid').where(productid: 'abc')

#<MyModel:0x0000ffff8f682448> {
         "productid" => "abc",
         "sum(units)" => "999"
    }
```

This also does not work (alias name on sum column != column name) leads to int value being cast to string:
```
=> MyModel.select("productid,sum(units) as my_units").group('productid').where(productid: 'abc')

#<MyModel:0x0000ffff8f682448> {
         "productid" => "abc",
         "my_units" => "999"
    }
```

It looks like the type casting happens whenever the adapter is unable to detect the column used, i.e. "sum(units)" isn't detected as being the units column, and also "sum(units) as my_units" isn't. This flaw does not exist for example in the MySQL adapter.

Because we are using higher level query builders (i.e. [ActiveCube](https://github.com/bitquery/activecube)) and have no control over the aliases used in the queries, it's mandatory that it is handled correctly on the adapter level.

**Comment by jbwl** [comment]
closing this as I was not using the rails_7 branch. Bug still exists there, so I'm reopening over there

**Comment by PNixx** [comment]
Fixed in https://github.com/PNixx/clickhouse-activerecord/commit/191ac67ed5eba2e1cbd20306d855b85b603e54d4

**Comment by jbwl** [comment]
Sorry to bother, but could you fix this for the rails_7 branch also, please? Currently it's still at 0.5.15.
Thank you so much!

**Comment by PNixx** [comment]
Use can use:
```
gem 'clickhouse-activerecord', github: 'PNixx/clickhouse-activerecord', branch: 'rails_7'
```

**Comment by jbwl** [comment]
Yes, this is the exact line in my Gemfile, but still 0.5.15 will be installed by Bundler. It does not have the fix for typecasting.

**Comment by PNixx** [comment]
latest v0.6.0

**Comment by PNixx** [comment]
rails_7 minimum required Rails 7.1
