### ISSUE TITLE
Mutation-based updates using ALTER…UPDATE

### ISSUE THREAD

**Issue by daya** [PNixx/clickhouse-activerecord#93]
Does this gem support Mutation-based updates using [ALTER…UPDATE](https://clickhouse.com/docs/en/sql-reference/statements/alter/update/) in case of irregular and non-frequent changes ?

see https://clickhouse.com/docs/en/sql-reference/statements/alter/update/

**Comment by PNixx** [comment]
Released in v1.0.1
