### ISSUE TITLE
Datetime precision issue

### ISSUE THREAD

**Issue by romamur** [PNixx/clickhouse-activerecord#95]
I have gems clickhouse 0.1.10, clickhouse-activerecord 0.5.14, pg 1.4.6 and rails 7.0.4.3. ClickHouse server version 23.4.2.11, postgresql server 15.3.
My clickhouse table ddl:
```sql
create table default.tests
(
    id         UUID default generateUUIDv4(),
    created_at DateTime64(6)
)
engine = MergeTree PARTITION BY toMonth(created_at) ORDER BY (id, created_at);
```
My model is Test. When i create record like:
```ruby
Test.create
```
this produces sql query:
```sql
INSERT INTO tests (created_at) VALUES ('2023-06-10 08:41:57')
```
As you can see there is no precision (microseconds).
I can define rails time db format like this:
```ruby
Time::DATE_FORMATS[:db] = '%Y-%m-%d %H:%M:%S.%6N'
```
then if i create record this will produce correct result:
```sql
INSERT INTO tests (created_at) VALUES ('2023-06-10 08:41:57.123123')
```
But this broke my PostgreSQL models sql queries! For example if i have model PgTest and if i create record like this:
```ruby
PgTest.create
```
this will produce incorrect precision sql query in my postgresql database (duplicate precision):
```sql
INSERT INTO pg_tests (created_at) VALUES ('2023-06-10 08:41:57.123123.123123')
```
Setting Time db format in callback around_create - not an option for me.

**Comment by romamur** [comment]
Thanks for fix, but i have upgraded gem to 0.5.15 and this doesn't work :(
This produces sql query (there is no precision):
```sql
INSERT INTO tests (created_at) VALUES ('2023-06-10 08:41:57')
```
My Gemfile.lock:
```text
clickhouse (0.1.10)
      activesupport (>= 4.1.8)
      bundler (>= 1.13.4)
      erubis
      faraday
      launchy
      pond
      sinatra
      thor
clickhouse-activerecord (0.5.15)
      activerecord (>= 5.2)
      bundler (>= 1.13.4)
```

**Comment by PNixx** [comment]
https://github.com/PNixx/clickhouse-activerecord/blob/master/spec/cases/model_spec.rb#L77-L86 check this test

**Comment by romamur** [comment]
![image](https://github.com/PNixx/clickhouse-activerecord/assets/36655656/3507c8e7-5635-4fd9-8553-01dbe819cb48)

**Comment by PNixx** [comment]
I checked, it not working with Rails 7, working with only Rails 6

**Comment by PNixx** [comment]
Please, check from [rails_7](https://github.com/PNixx/clickhouse-activerecord/tree/rails_7) branch

**Comment by romamur** [comment]
Worked on rails_7 branch 🎉
![image](https://github.com/PNixx/clickhouse-activerecord/assets/36655656/1adb05fa-b7fa-4356-ab9e-0624f9791200)
