### ISSUE TITLE
Update to Rails 7 Static type mapping

### ISSUE THREAD

**Issue by quorauk** [PNixx/clickhouse-activerecord#96]
Related to: https://github.com/rails/rails/pull/42773

Also referenced in this issue
https://github.com/PNixx/clickhouse-activerecord/issues/68

I was thinking of picking up this migration during our workplace open source time. We use this adapter in one of our projects and are currently monkey patching this issue.

We can also see that you are doing some work on this in the [rails 7](https://github.com/PNixx/clickhouse-activerecord/tree/rails_7) branch.

Are you interested in us picking this up and submitting a PR for this? 

Do you have any guidelines we should be aware of outside of the Code of Conduct?

Thanks!

**Comment by PNixx** [comment]
Yes, you can push PR
