### ISSUE TITLE
Rails 7.1 - NoMethodError: undefined method `table_exists?' for ClickhouseActiverecord::SchemaMigration:Class

### ISSUE THREAD

**Issue by spyderdfx** [PNixx/clickhouse-activerecord#99]
Fails here https://github.com/PNixx/clickhouse-activerecord/blob/aaa11f66719265bd1a9289e1cf04ef9a33eed608/lib/clickhouse-activerecord/migration.rb#L9

Looks like `.table_exists?` is now an instance method https://github.com/rails/rails/blob/52c4aefcd65d07352e28145ca1f52ab0b2f64ebe/activerecord/lib/active_record/schema_migration.rb#L85

Also https://github.com/rails/rails/pull/45908

**Comment by PNixx** [comment]
Fixed in `rails_7` branch
